# Commands to start on workspace startup
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 300` 
      echo "Startting Dev Server 😉 ...."
      npm run dev

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-browser

# VS Code Extentions
vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true